environment:
  name: dev
  project: cdf-bootcamp-01-test # Your CDF project
  type: dev #prod, staging or dev
  selected:
    - modules/data_foundation
    - modules/ice_cream_api
    - modules/uc_oee

variables:
  CDF_PROJECT: cdf-bootcamp-01-test
  IDP_CLIENT_ID: ${IDP_CLIENT_ID}
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
  IDP_TENANT_ID: 16e3985b-ebe8-4e24-9da4-933e21a9fc81 # Since we all have the same tenant, this number does not change
  CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
  IDP_SCOPES: https://westeurope-1.cognitedata.com/.default

  # Groups
  data_developer_source_id: 1d176994-9566-4f3a-873a-6ed5191bb16c # data_developer
  oee_data_pipeline_source_id: 1d176994-9566-4f3a-873a-6ed5191bb16c
  readwrite_source_id: 4b5a25e0-dae5-4496-b840-e7533e498d8e
  readonly_source_id: 8a2332a5-90b3-4a79-bfe4-85b6e902b4b4
  icapi_extractors_source_id: e7f0242d-5b79-48ec-8738-40f198670332

  # Client Ids
  sp_oee_client_id: 381abe9b-4039-40ff-8333-3dc47245f59d
  sp_oee_client_secret: ${IDP_OEE_CLIENT_SECRET}
  icapi_extractors_client_id: 6870346b-68a8-4a8e-b7da-d63643be18e7
  icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

  modules:
    icapi_ds_external_id: ds_ice_cream_api
    uc_oee:
      uc_oee_ds_external_id: ds_uc_oee
